name: 'AppCenter distribute GitHub action'
description: 'AppCenter distribute GitHub action'
inputs:
  token:
    description: 'API token (App API token or User API token)'
    required: true
    default: ''
  path:
    description: 'ipa or apk file path'
    required: true
    default: ''
  app:
    description: 'Specify app in the <ownerName>/<appName> format'
    required: true
    default: ''
  mandatory:
    description: 'Make the release mandatory for the testers'
    required: false
    default: false
  silent:
    description: 'Do not notify testers of this release'
    required: false
    default: false
  group:
    description: 'Comma-separated distribution group names'
    required: false
    default: ''
  release_notes:
    description: 'Release notes text (5000 characters max)'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
