name: Build & Test [iOS]

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

env:
  APPCENTER_DISTRIBUTION_GROUP: Testers

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Distribute ipa to App Center
        uses: ./
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          path: ${{ github.repository }}/Unity-Empty-Project.ipa
          app: akiojin/Unity-Empty-Project-iOS
          mandatory: true
          silent: false
          group: ${{ env.APPCENTER_DISTRIBUTION_GROUP }}
          release_notes: |
            - GitHub Actions
              - Action : ${{ github.event_name }}
              - Requester : ${{ github.actor }}
              - Build Number : ${{ github.run_number }}
              - Commit Message : ${{ github.event.head_commit.message }}
