name: Build & Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

env:
  APPCENTER_DISTRIBUTION_GROUP: Testers

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        artifact: [ 'ipa', 'apk' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install & npm install -g appcenter-cli

      - name: Distribute ipa to App Center
        uses: ./
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/Unity-Empty-Project.${{ matrix.artifact }}
          app: akiojin/Unity-Empty-Project-${{ fromJSON('["iOS", "Android"]')[${{ matrix.artifact }} == 'apk'] }}
          mandatory: true
          silent: false
          group: ${{ env.APPCENTER_DISTRIBUTION_GROUP }}
          release_notes: |
            "# GitHub Actions
            - Action : ${{ github.event_name }}
            - Requester : ${{ github.actor }}
            - Build Number : ${{ github.run_number }}
            - Commit Message : ${{ github.event.head_commit.message }}"
