name: Testing distribute

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

env:
  APPCENTER_DISTRIBUTION_GROUP: Testers

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, Windows-latest ]
        target: [ 'iOS', 'Android' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install & npm install -g appcenter-cli

      - name: token is null
        uses: ./
        continue-on-error: true

      - name: path is null
        uses: ./
        continue-on-error: true
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          app: akiojin/Unity-Empty-Project-${{ matrix.target }}-${{ matrix.os }}

      - name: app is null
        uses: ./
        continue-on-error: true
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          path: ${{ github.workspace }}/artifacts/Unity-Empty-Project.${{ fromJSON('["ipa", "apk"]')[matrix.target == 'Android'] }}

      - uses: ./
        with:
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
          build-number: ${{ github.run_number }}
          path: ${{ github.workspace }}/artifacts/Unity-Empty-Project.${{ fromJSON('["ipa", "apk"]')[matrix.target == 'Android'] }}
          app: akiojin/Unity-Empty-Project-${{ matrix.target }}-${{ matrix.os }}
          mandatory: true
          silent: false
          group: ${{ env.APPCENTER_DISTRIBUTION_GROUP }}
          release_notes: |
            "# GitHub Actions
            - Action : ${{ github.event_name }}
            - Requester : ${{ github.actor }}
            - Build Number : ${{ github.run_number }}
            - Commit Message : ${{ github.event.head_commit.message }}"
